"""Change Verification status from boolean to enum type

Revision ID: 09106b6eef5a
Revises: 
Create Date: 2025-05-10 16:21:20.974406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '09106b6eef5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_organization_id', table_name='payments')
    # op.create_unique_constraint(None, 'services', ['external_api_config_id'])
    op.create_foreign_key(None, 'services', 'external_api_configs', ['external_api_config_id'], ['id'])
    op.alter_column('transfers', 'amount',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('transfers', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('transfers', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('transfers', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    # op.drop_index('idx_from_user_id', table_name='transfers')
    # op.drop_index('idx_organization_id', table_name='transfers')
    # op.drop_index('idx_to_bank_account_id', table_name='transfers')
    op.create_index(op.f('ix_transfers_id'), 'transfers', ['id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('O_CONVENER', 'E_ADMIN', 'T_ADMIN', 'SENIOR_E_ADMIN', 'DATA_USER', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('T_ADMIN', 'E_ADMIN', 'SENIOR_E_ADMIN', 'O_CONVENER', 'DATA_USER', name='userrole'),
               nullable=True)
    op.alter_column('verification_status', 'e_admin_approved',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Enum('PENDING', 'APPROVAL', 'REJECTION', name='verificationstatusenum'),
               existing_nullable=True)
    op.alter_column('verification_status', 'senior_approved',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Enum('PENDING', 'APPROVAL', 'REJECTION', name='verificationstatusenum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_status', 'senior_approved',
               existing_type=sa.Enum('PENDING', 'APPROVAL', 'REJECTION', name='verificationstatusenum'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('verification_status', 'e_admin_approved',
               existing_type=sa.Enum('PENDING', 'APPROVAL', 'REJECTION', name='verificationstatusenum'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('T_ADMIN', 'E_ADMIN', 'SENIOR_E_ADMIN', 'O_CONVENER', 'DATA_USER', name='userrole'),
               type_=mysql.ENUM('O_CONVENER', 'E_ADMIN', 'T_ADMIN', 'SENIOR_E_ADMIN', 'DATA_USER', collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.drop_index(op.f('ix_transfers_id'), table_name='transfers')
    op.create_index('idx_to_bank_account_id', 'transfers', ['to_bank_account_id'], unique=False)
    op.create_index('idx_organization_id', 'transfers', ['organization_id'], unique=False)
    # op.create_index('idx_from_user_id', 'transfers', ['from_user_id'], unique=False)
    op.alter_column('transfers', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('transfers', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('transfers', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('transfers', 'amount',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.drop_constraint(None, 'services', type_='foreignkey')
    # op.drop_constraint(None, 'services', type_='unique')
    # op.create_index('idx_organization_id', 'payments', ['organization_id'], unique=False)
    # ### end Alembic commands ###
