"""update organization columns

Revision ID: 4491629e0d16
Revises: b910ac4b9bd5
Create Date: 2025-05-17 12:08:16.124085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4491629e0d16'
down_revision: Union[str, None] = 'b910ac4b9bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'organizations',
        'description',
        new_column_name='full_name',
        existing_type=sa.Text(),
        existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'organizations',
        'full_name',
        new_column_name='description',
        existing_type=sa.Text(),
        existing_nullable=True
    )
    # ### end Alembic commands ###
